[package]
name = "openml"
version = "0.1.0"
authors = ["Martin Billinger <flkazemakase@gmail.com>"]

[dependencies]
arff = { path = "../arff" }
futures = "0.1"
hyper = "0.11"
hyper-tls = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio-core = "0.1"
